### ISSUE TITLE
Not working with Preact

### ISSUE THREAD

**Issue by kunjee17** [Zaid-Ajaj/Fable.React.Flatpickr#3] opened 2018-06-20 11:50 UTC
Hi, 

I have no idea but it was perfectly working with Preact earlier. but recently it is stopped working. And when I switched to react. It starts working. Again don't know why. Can you please help me debug this one or if you are have time please have a look.

**Comment by Zaid-Ajaj** [comment] 2018-06-20 12:33
Yeah definitely, do you have a repro where it isn't working so I could have a look at it? My first guess is that your preact version (or [preact-compat](https://github.com/developit/preact-compat)) is updated to something incompatible

**Comment by kunjee17** [comment] 2018-06-20 12:34
I have tried with infernojs and it is working as it should.

**Comment by kunjee17** [comment] 2018-06-20 12:34
@Zaid-Ajaj I ll try to have reproduce in weekend... 👍

**Comment by Zaid-Ajaj** [comment] 2018-07-20 01:13
Did you manage to get the component working with Preact? 

> If so, would be nice to share for others having the same issue :smile:

**Comment by kunjee17** [comment] 2018-07-20 08:11
@Zaid-Ajaj didn't got time to work on that. I did moved project to react as preact and inferno both were giving issues here and there...

**Comment by Zaid-Ajaj** [comment] 2018-07-20 11:17
Compatibility issues strike again 😓 

Alright, I will close this for now because I can't reproduce the issue, anyone please reopen if you encounter it with a concrete example

**Closed as completed by Zaid-Ajaj** 2018-07-20 11:17 UTC
